// Refactored: uses Cloudflare Dynamic Workers (env.LOADER) for invoke.
// Deploy only writes to KV; no CF API calls needed.
// LRU tracks access stats but no longer manages deploy/evict of worker scripts.

import type { SigilBackend, DeployParams, DeployResult, Capability, BackendStatus, QueryParams, QueryResult, QueryItem, ResolveInvokeResult, ResolveInvokeError } from './types.js'
import { KvStore } from '../kv.js'
import { LruScheduler } from '../lru.js'
import { CONFIG } from '../config.js'
import { EmbeddingService, cosineSimilarity, mmrSelect } from '../embedding.js'

/**
 * Dynamic Workers loader binding type.
 * env.LOADER.get(id, callback) caches a worker by id; callback loads on miss.
 * env.LOADER.load(config) creates a one-shot worker.
 */
export interface WorkerLoader {
  get(id: string, loader: () => Promise<DynamicWorkerConfig> | DynamicWorkerConfig): DynamicWorkerHandle
  load(config: DynamicWorkerConfig): DynamicWorkerHandle
}

export interface DynamicWorkerConfig {
  compatibilityDate: string
  mainModule: string
  modules: Record<string, string>
  globalOutbound?: null  // null = block network access
}

export interface DynamicWorkerHandle {
  getEntrypoint(name?: string): { fetch(request: Request): Promise<Response> }
}

export class WorkerPool implements SigilBackend {
  private kv: KvStore
  private lru: LruScheduler
  private embeddingService: EmbeddingService
  private config = CONFIG

  constructor(
    kv: KVNamespace,
    private loader: WorkerLoader,
    embeddingService: EmbeddingService,
  ) {
    this.kv = new KvStore(kv)
    this.lru = new LruScheduler(this.kv)
    this.embeddingService = embeddingService
  }

  private async generateHash(input: string): Promise<string> {
    const encoder = new TextEncoder()
    const data = encoder.encode(input)
    const hashBuffer = await crypto.subtle.digest('SHA-256', data)
    const hashArray = Array.from(new Uint8Array(hashBuffer))
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('').slice(0, this.config.HASH_LENGTH)
  }

  private getWorkerName(capability: string): string {
    return `${this.config.WORKER_PREFIX}${capability}`
  }

  async deploy(params: DeployParams): Promise<DeployResult> {
    const { name, code, schema, type, ttl, bindings, description, tags, examples } = params

    if (!code) {
      throw new Error('deploy: code is required (should be pre-generated by router)')
    }

    // Determine capability name
    let capability: string
    if (name === null) {
      const hash = await this.generateHash(code + Date.now())
      capability = `t-${hash}`
    } else {
      capability = name
    }

    const workerName = this.getWorkerName(capability)
    const now = Date.now()

    // Write KV entries (no CF API deploy needed — code is loaded dynamically at invoke time)
    await this.kv.setCode(capability, code)
    await this.kv.setMeta(capability, {
      type,
      ttl,
      created_at: now,
      bindings,
      description,
      tags,
      examples,
      schema,
    })
    await this.kv.setLru(capability, {
      last_access: now,
      access_count: 0,
      deployed: true,  // always "deployed" since code is in KV
    })
    await this.kv.setRoute(capability, {
      worker_name: workerName,
    })

    // Compute and store embedding
    try {
      const text = EmbeddingService.buildCapabilityText({
        name: capability,
        description,
        tags,
        examples,
      })
      const vector = await this.embeddingService.embed(text)
      await this.kv.setEmbedding(capability, vector)
    } catch (e) {
      console.error('[sigil] embedding error during deploy:', e)
    }

    const url = `${this.config.GATEWAY_URL}/run/${capability}`
    const result: DeployResult = {
      capability,
      url,
      cold_start: false,
    }

    if (type === 'ephemeral' && ttl !== undefined) {
      result.expires_at = new Date(now + ttl * 1000).toISOString()
    }

    return result
  }

  /**
   * Invoke a capability using Dynamic Workers.
   * LOADER.get() caches warm instances; callback only fires on cache miss.
   */
  async invoke(capabilityName: string, request: Request): Promise<Response> {
    const code = await this.kv.getCode(capabilityName)
    if (!code) {
      return new Response(JSON.stringify({ error: 'Capability not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Update LRU access stats
    const lru = await this.kv.getLru(capabilityName)
    if (lru) {
      await this.kv.setLru(capabilityName, {
        ...lru,
        last_access: Date.now(),
        access_count: lru.access_count + 1,
        deployed: true,
      })
    }

    // Use Dynamic Workers to load and execute the capability code.
    // LOADER.get() caches by id — subsequent requests reuse the warm instance.
    const worker = this.loader.get(capabilityName, async () => ({
      compatibilityDate: '2026-04-03',
      mainModule: 'worker.js',
      modules: { 'worker.js': code },
    }))

    return worker.getEntrypoint().fetch(request)
  }

  /**
   * resolveInvoke is no longer needed (was used for 302 redirect workaround).
   * Kept for interface compatibility; delegates to invoke internally.
   */
  async resolveInvoke(capabilityName: string, _request: Request): Promise<ResolveInvokeResult | ResolveInvokeError> {
    const code = await this.kv.getCode(capabilityName)
    if (!code) {
      return { error: 'Capability not found', status: 404 }
    }
    // Return a synthetic result; actual invocation now goes through invoke()
    return { subdomain: '', cold_start: false }
  }

  async remove(capabilityName: string): Promise<void> {
    // Just clean KV — no CF API script to delete
    await this.kv.deleteCode(capabilityName)
    await this.kv.deleteMeta(capabilityName)
    await this.kv.deleteLru(capabilityName)
    await this.kv.deleteRoute(capabilityName)
    await this.kv.deleteEmbedding(capabilityName)
  }

  async query(params: QueryParams): Promise<QueryResult> {
    const { q, mode: rawMode, limit: rawLimit, cursor } = params

    const mode = rawMode ?? (q ? 'find' : 'explore')
    const defaultLimit = mode === 'find' ? 3 : 20
    const limit = rawLimit ?? defaultLimit

    const caps = await this.kv.listCapabilities()

    if (!q) {
      const allCapabilities: Capability[] = []

      for (const cap of caps) {
        const meta = await this.kv.getMeta(cap)
        const lru = await this.kv.getLru(cap)
        if (!meta || !lru) continue

        const capability: Capability = {
          capability: cap,
          type: meta.type,
          deployed: lru.deployed,
          last_access: lru.last_access,
          access_count: lru.access_count,
          created_at: meta.created_at,
          description: meta.description,
          tags: meta.tags,
          examples: meta.examples,
        }

        if (meta.ttl !== undefined) {
          capability.ttl = meta.ttl
          capability.expires_at = new Date(meta.created_at + meta.ttl * 1000).toISOString()
        }

        allCapabilities.push(capability)
      }

      const sorted = allCapabilities.sort((a, b) => b.created_at - a.created_at)
      const items: QueryItem[] = sorted.map(cap => ({
        capability: cap.capability,
        description: cap.description,
        type: cap.type,
        score: 1.0,
      }))

      const offset = cursor ? parseInt(cursor, 10) : 0
      const total = items.length
      const paged = items.slice(offset, offset + limit)

      return { total, items: paged }
    }

    const queryVec = await this.embeddingService.embedQuery(q)

    const embeddingCandidates: Array<{
      capability: string
      vector: number[]
      meta: any
      lru: any
    }> = []
    const fallbackCandidates: Capability[] = []

    for (const cap of caps) {
      const vector = await this.kv.getEmbedding(cap)
      const meta = await this.kv.getMeta(cap)
      const lru = await this.kv.getLru(cap)
      if (!meta || !lru) continue

      if (vector) {
        embeddingCandidates.push({ capability: cap, vector, meta, lru })
      } else {
        fallbackCandidates.push({
          capability: cap,
          type: meta.type,
          deployed: lru.deployed,
          last_access: lru.last_access,
          access_count: lru.access_count,
          created_at: meta.created_at,
          description: meta.description,
          tags: meta.tags,
          examples: meta.examples,
          schema: meta.schema,
        })
      }
    }

    const qLower = q.toLowerCase()
    const fallbackItems: QueryItem[] = fallbackCandidates
      .filter(cap => {
        return (
          cap.capability.toLowerCase().includes(qLower) ||
          cap.description?.toLowerCase().includes(qLower) ||
          cap.tags?.some(t => t.toLowerCase().includes(qLower))
        )
      })
      .map(cap => ({
        capability: cap.capability,
        description: cap.description,
        tags: cap.tags,
        examples: cap.examples,
        type: cap.type,
        deployed: cap.deployed,
        access_count: cap.access_count,
        score: 0.5,
        schema: cap.schema,
      }))

    const effectiveMode = (mode === 'find' && !q) ? 'explore' : mode

    if (effectiveMode === 'find') {
      const scored = embeddingCandidates
        .map(c => ({
          ...c,
          score: cosineSimilarity(queryVec, c.vector),
        }))
        .filter(c => c.score > 0.3)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)

      const embeddingItems: QueryItem[] = scored.map(c => ({
        capability: c.capability,
        description: c.meta.description,
        tags: c.meta.tags,
        examples: c.meta.examples,
        type: c.meta.type,
        deployed: c.lru.deployed,
        access_count: c.lru.access_count,
        score: Math.round(c.score * 1000) / 1000,
        schema: c.meta.schema,
      }))

      const embeddingCaps = new Set(embeddingItems.map(i => i.capability))
      const fallbackOnly = fallbackItems.filter(i => !embeddingCaps.has(i.capability))
      const items = [...embeddingItems, ...fallbackOnly]
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)

      const offset = cursor ? parseInt(cursor, 10) : 0
      const total = items.length
      return { total, items: items.slice(offset, offset + limit) }
    } else {
      const results = mmrSelect(queryVec, embeddingCandidates, limit, 0.5)

      const embeddingItems: QueryItem[] = results
        .filter(r => r.score > 0.2)
        .map(r => ({
          capability: r.capability,
          description: r.meta.description,
          type: r.meta.type,
          score: Math.round(r.score * 1000) / 1000,
        }))

      const embeddingCaps = new Set(embeddingItems.map(i => i.capability))
      const fallbackOnly = fallbackItems
        .filter(i => !embeddingCaps.has(i.capability))
        .map(({ capability, description, type, score }) => ({ capability, description, type, score }))

      const items = [...embeddingItems, ...fallbackOnly]
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)

      const offset = cursor ? parseInt(cursor, 10) : 0
      const total = items.length
      return { total, items: items.slice(offset, offset + limit) }
    }
  }

  async inspect(capabilityName: string): Promise<Capability | null> {
    const meta = await this.kv.getMeta(capabilityName)
    const lru = await this.kv.getLru(capabilityName)
    if (!meta || !lru) return null

    const capability: Capability = {
      capability: capabilityName,
      type: meta.type,
      deployed: lru.deployed,
      last_access: lru.last_access,
      access_count: lru.access_count,
      created_at: meta.created_at,
    }

    if (meta.ttl !== undefined) {
      capability.ttl = meta.ttl
      capability.expires_at = new Date(meta.created_at + meta.ttl * 1000).toISOString()
    }

    return capability
  }

  async status(): Promise<BackendStatus> {
    const caps = await this.kv.listCapabilities()
    const evictionCount = await this.kv.getEvictionCount()

    return {
      backend: 'worker-pool',
      total_slots: this.config.MAX_SLOTS,
      used_slots: caps.length,  // All capabilities with code in KV are "deployed"
      lru_enabled: true,
      eviction_count: evictionCount,
    }
  }
}
